version: '3.4'

services:
  webapp:
    build: ./OAuth
    ports:
      - 5002:80
      - 5003:443
      - 5004:5000
      - 5001:5001
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80;https://+:5001;http://+:5000;
      - ASPNETCORE_Kestrel__Certificates__Default__Password=local
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro